@startuml

title __REPOSITORY's Class Diagram__\n

  namespace tech.eportfolio.server {
    namespace repository {
      interface tech.eportfolio.server.repository.PortfolioRepository {
          {abstract} + findByUserIdInAndDeleted()
          {abstract} + findByUsername()
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace repository {
      interface tech.eportfolio.server.repository.TagRepository {
          {abstract} + findByDeleted()
          {abstract} + findByIdAndDeleted()
          {abstract} + findByIdInAndDeleted()
          {abstract} + findByNameAndDeleted()
          {abstract} + findByNameInAndDeleted()
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace repository {
      interface tech.eportfolio.server.repository.TemplateRepository {
          {abstract} + findAllByHiddenAndDeleted()
          {abstract} + findByIdAndHiddenAndDeleted()
          {abstract} + findByTitleAndDeleted()
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace repository {
      interface tech.eportfolio.server.repository.UserCommentRepository {
          {abstract} + findByPortfolioIdAndDeleted()
          {abstract} + findByUsernameAndDeleted()
          {abstract} + findByUsernameAndIdAndDeleted()
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace repository {
      interface tech.eportfolio.server.repository.UserFollowRepository {
          {abstract} + findByDestinationUsernameAndDeleted()
          {abstract} + findBySourceUsernameAndDestinationUsername()
          {abstract} + findBySourceUsernameAndDestinationUsernameAndDeleted()
          {abstract} + findBySourceUsernameAndIdAndDeleted()
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace repository {
      interface tech.eportfolio.server.repository.UserLikeRepository {
          {abstract} + findByPortfolioIdAndDeleted()
          {abstract} + findByPortfolioIdAndUsernameAndDeleted()
          {abstract} + findByUsernameAndDeleted()
          {abstract} + findByUsernameAndPortfolioId()
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace repository {
      interface tech.eportfolio.server.repository.UserRepository {
          {abstract} + countAllByDeleted()
          {abstract} + findByDeletedAndUpdatedDateBeforeAndBlobUUIDIsNotNull()
          {abstract} + findByEmailAndDeleted()
          {abstract} + findByIdInAndDeleted()
          {abstract} + findByUsernameAndDeleted()
          {abstract} + findByUsernameInAndDeleted()
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace repository {
      interface tech.eportfolio.server.repository.UserTagRepository {
          {abstract} + findBy()
          {abstract} + findByTagIdAndDeleted()
          {abstract} + findByTagIdInAndUsernameAndDeleted()
          {abstract} + findByUsernameAndDeleted()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
