@startuml
skinparam linetype polyline
skinparam dpi 300

title __CONTROLLER's Class Diagram__\n

skinparam linetype ortho

      class tech.eportfolio.server.controller.AuthenticationController {
          - authenticationManager : AuthenticationManager
          - logger : Logger
          - refreshKey : String
          - signKey : String
          + AuthenticationController()
          + generatePasswordRecoveryLink()
          + generatePasswordRecoveryToken()
          + login()
          + renewToken()
          + sendPasswordRecoveryLink()
          + signUp()
          + verifyPasswordReset()
          - authenticate()
          - generateTokens()
      }
      class tech.eportfolio.server.controller.BlobController {
          - logger : Logger
          + BlobController()
          + deleteBlob()
          + getBlobs()
          + uploadBlob()
          + uploadImage()
      }

      class tech.eportfolio.server.controller.FeedController {
          - objectMapper : ObjectMapper
          + FeedController()
          + getActives()
      }

      class tech.eportfolio.server.controller.PortfolioController {
          {static} + CONTENT : String
          {static} + PORTFOLIO : String
          - objectMapper : ObjectMapper
          + PortfolioController()
          + createNewPortfolio()
          + deleteContent()
          + findByUsername()
          + findContentByUsername()
          + updatePortfolio()
          + uploadContent()
      }

      class tech.eportfolio.server.controller.SearchController {
          - objectMapper : ObjectMapper
          + SearchController()
          + searchByKeyword()
          + searchByTag()
          - addVisibilities()
      }

      class tech.eportfolio.server.controller.TagController {
          + createNewTag()
          + findAll()
          + findOneTag()
      }

      class tech.eportfolio.server.controller.TemplateController {
          - logger : Logger
          + TemplateController()
          + createTemplate()
          + deleteTemplate()
          + findAllTemplates()
          + findOneById()
      }

      class tech.eportfolio.server.controller.TestController {
          - logger : Logger
          + deleteTest()
          + letMeLogIn()
          + notifyTest()
          + quickTest()
          + setJwtTokenProvider()
          + setPortfolioService()
          + setUserFollowService()
          + setUserRepository()
          + setUserService()
          - createTestUser()
      }

      class tech.eportfolio.server.controller.UserCommentController {
          {static} - COMMENTS : String
          + UserCommentController()
          + createComment()
          + findWhoCommentedThisPortfolio()
          + reply()
          + uncommentPortfolio()
      }

      class tech.eportfolio.server.controller.UserController {
          + UserController()
          + addUserTag()
          + deleteUserTags()
          + findOneUser()
          + getUserTags()
          + passwordReset()
          + updateUser()
      }

      class tech.eportfolio.server.controller.UserFollowController {
          + UserFollowController()
          + findWhoFollowedThisUser()
          + findWhoIamFollowing()
          + followUser()
          + unfollowUser()
      }

      class tech.eportfolio.server.controller.UserLikeController {
          + UserLikeController()
          + findWhoLikedThisPortfolio()
          + likePortfolio()
          + unlikePortfolio()
      }

      class tech.eportfolio.server.controller.VerificationController {
          + VerificationController()
          + generateLink()
          + generateToken()
          + resend()
          + verify()
      }


  tech.eportfolio.server.controller.AuthenticationController -up-|> tech.eportfolio.server.common.exception.handler.AuthenticationExceptionHandler
  tech.eportfolio.server.controller.AuthenticationController -[hidden]> tech.eportfolio.server.common.exception.handler.AuthenticationExceptionHandler
  tech.eportfolio.server.controller.AuthenticationController o-- tech.eportfolio.server.common.utility.JWTTokenProvider
  tech.eportfolio.server.controller.AuthenticationController o-- tech.eportfolio.server.service.RecoveryService
  tech.eportfolio.server.controller.AuthenticationController o-- tech.eportfolio.server.common.unsplash.Client
  tech.eportfolio.server.controller.AuthenticationController o-- tech.eportfolio.server.service.UserService
  tech.eportfolio.server.controller.AuthenticationController o-- tech.eportfolio.server.service.VerificationService

  tech.eportfolio.server.controller.BlobController -up-|> tech.eportfolio.server.common.exception.handler.AuthenticationExceptionHandler
  tech.eportfolio.server.controller.BlobController -[hidden]> tech.eportfolio.server.common.exception.handler.AuthenticationExceptionHandler
  tech.eportfolio.server.controller.BlobController o-- tech.eportfolio.server.service.AzureStorageService
  tech.eportfolio.server.controller.BlobController -[hidden]-> tech.eportfolio.server.service.AzureStorageService
  tech.eportfolio.server.controller.BlobController o-- tech.eportfolio.server.service.UserService

  tech.eportfolio.server.controller.FeedController -[hidden]-> tech.eportfolio.server.service.ActivityService
  tech.eportfolio.server.controller.FeedController o--- tech.eportfolio.server.service.ActivityService
  tech.eportfolio.server.controller.FeedController o--- tech.eportfolio.server.service.PortfolioService
  tech.eportfolio.server.controller.FeedController o--- tech.eportfolio.server.service.TagService
  tech.eportfolio.server.controller.FeedController o--- tech.eportfolio.server.service.UserFollowService
  tech.eportfolio.server.controller.FeedController o--- tech.eportfolio.server.service.UserService

  tech.eportfolio.server.controller.PortfolioController -[hidden]-> tech.eportfolio.server.service.PortfolioService
  tech.eportfolio.server.controller.PortfolioController o-- tech.eportfolio.server.service.PortfolioService
  tech.eportfolio.server.controller.PortfolioController o-- tech.eportfolio.server.service.UserService

  tech.eportfolio.server.controller.SearchController o-- tech.eportfolio.server.service.PortfolioService
  tech.eportfolio.server.controller.SearchController o-- tech.eportfolio.server.service.TagService
  tech.eportfolio.server.controller.SearchController o-- tech.eportfolio.server.service.UserService
  tech.eportfolio.server.controller.SearchController o-- tech.eportfolio.server.service.UserTagService

  tech.eportfolio.server.controller.TagController -[hidden]-> tech.eportfolio.server.service.TagService
  tech.eportfolio.server.controller.TagController o-- tech.eportfolio.server.service.TagService

  tech.eportfolio.server.controller.TemplateController -[hidden]-> tech.eportfolio.server.service.TemplateService
  tech.eportfolio.server.controller.TemplateController o-- tech.eportfolio.server.service.TemplateService
  tech.eportfolio.server.controller.TemplateController o-- tech.eportfolio.server.service.UserService


  tech.eportfolio.server.controller.TestController o-- tech.eportfolio.server.common.utility.JWTTokenProvider
  tech.eportfolio.server.controller.TestController o-- tech.eportfolio.server.service.PortfolioService
  tech.eportfolio.server.controller.TestController o-- tech.eportfolio.server.service.UserFollowService
  tech.eportfolio.server.controller.TestController o-- tech.eportfolio.server.repository.UserRepository
  tech.eportfolio.server.controller.TestController o-- tech.eportfolio.server.service.UserService

  tech.eportfolio.server.controller.UserCommentController -[hidden]-> tech.eportfolio.server.service.UserCommentService
  tech.eportfolio.server.controller.UserCommentController o-- tech.eportfolio.server.service.UserCommentService
  tech.eportfolio.server.controller.UserCommentController o-- tech.eportfolio.server.service.PortfolioService
  tech.eportfolio.server.controller.UserCommentController -[hidden]-> tech.eportfolio.server.service.UserCommentService
  tech.eportfolio.server.controller.UserCommentController o-- tech.eportfolio.server.service.UserService

  tech.eportfolio.server.controller.UserController -[hidden]-> tech.eportfolio.server.service.UserService
  tech.eportfolio.server.controller.UserController o-- tech.eportfolio.server.service.UserService
  tech.eportfolio.server.controller.UserController o-- tech.eportfolio.server.service.UserTagService

  tech.eportfolio.server.controller.UserFollowController -[hidden]-> tech.eportfolio.server.service.UserFollowService
  tech.eportfolio.server.controller.UserFollowController o-- tech.eportfolio.server.service.UserFollowService
  tech.eportfolio.server.controller.UserFollowController -[hidden]-> tech.eportfolio.server.service.UserFollowService
  tech.eportfolio.server.controller.UserFollowController o-- tech.eportfolio.server.service.UserService

  tech.eportfolio.server.controller.UserLikeController -[hidden]-> tech.eportfolio.server.service.UserLikeService
  tech.eportfolio.server.controller.UserLikeController o-- tech.eportfolio.server.service.PortfolioService
  tech.eportfolio.server.controller.UserLikeController o-- tech.eportfolio.server.service.UserLikeService
  tech.eportfolio.server.controller.UserLikeController -[hidden]-> tech.eportfolio.server.service.UserLikeService
  tech.eportfolio.server.controller.UserLikeController o-- tech.eportfolio.server.service.UserService

  tech.eportfolio.server.controller.VerificationController -[hidden]-> tech.eportfolio.server.service.VerificationService
  tech.eportfolio.server.controller.VerificationController o-- tech.eportfolio.server.service.UserService
  tech.eportfolio.server.controller.VerificationController o-- tech.eportfolio.server.service.VerificationService

@enduml