@startuml
skinparam dpi 300

title __Repository Class Diagram__\n

      interface tech.eportfolio.server.repository.ActivityRepository {
          {abstract} + findByIdNotInAndActivityTypeAndDeleted()
      }

      interface tech.eportfolio.server.repository.FeedHistoryRepository {
          {abstract} + findFeedHistoryByUserId()
      }

      interface tech.eportfolio.server.repository.PortfolioRepository {
          {abstract} + findByIdInAndDeleted()
          {abstract} + findByUserIdInAndDeleted()
          {abstract} + findByUsername()
      }

      interface tech.eportfolio.server.repository.TagRepository {
          {abstract} + findByDeleted()
          {abstract} + findByIdAndDeleted()
          {abstract} + findByIdInAndDeleted()
          {abstract} + findByNameAndDeleted()
          {abstract} + findByNameInAndDeleted()
      }

      interface tech.eportfolio.server.repository.TemplateRepository {
          {abstract} + findAllByHiddenAndDeleted()
          {abstract} + findByIdAndHiddenAndDeleted()
          {abstract} + findByTitleAndDeleted()
      }
      interface tech.eportfolio.server.repository.UserCommentRepository {
          {abstract} + findByPortfolioIdAndDeleted()
          {abstract} + findByUsernameAndDeleted()
          {abstract} + findByUsernameAndIdAndDeleted()
      }

      interface tech.eportfolio.server.repository.UserFollowRepository {
          {abstract} + findByDestinationUsernameAndDeleted()
          {abstract} + findBySourceUsernameAndDeleted()
          {abstract} + findBySourceUsernameAndDestinationUsername()
          {abstract} + findBySourceUsernameAndDestinationUsernameAndDeleted()
          {abstract} + findBySourceUsernameAndIdAndDeleted()
      }

      interface tech.eportfolio.server.repository.UserLikeRepository {
          {abstract} + findByPortfolioIdAndDeleted()
          {abstract} + findByPortfolioIdAndUsernameAndDeleted()
          {abstract} + findByUsernameAndDeleted()
          {abstract} + findByUsernameAndPortfolioId()
      }

      interface tech.eportfolio.server.repository.UserRepository {
          {abstract} + countAllByDeleted()
          {abstract} + findAllByDeleted()
          {abstract} + findByDeletedAndUpdatedDateBeforeAndBlobUUIDIsNotNull()
          {abstract} + findByEmailAndDeleted()
          {abstract} + findByIdInAndDeleted()
          {abstract} + findByUsernameAndDeleted()
          {abstract} + findByUsernameInAndDeleted()
      }

      interface tech.eportfolio.server.repository.UserTagRepository {
          {abstract} + findBy()
          {abstract} + findByTagIdAndDeleted()
          {abstract} + findByTagIdInAndUsernameAndDeleted()
          {abstract} + findByUsernameAndDeleted()
      }


@enduml
