sudo: required
language: java
jdk: oraclejdk11
services:
- docker
before_install:
- chmod +x gradlew

install:
- "./gradlew build"

after_success:
- docker login https://docker.pkg.github.com -u haswf -p $DOCKER_TOKEN
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
- export IMAGE_NAME=docker.pkg.github.com/haswf/comp30022backenddev/eportfolio-server-docker
- echo $COMMIT
- docker build --build-arg JAR_FILE=build/libs/*.jar -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
