azure:
    storage:
        connection-string: ${SPRING_AZURE_STORAGE_CONNECTION_STRING}
        container:
            name: ${SPRING_AZURE_STORAGE_CONTAINER_NAME}
unsplash:
    access:
        key: ${SPRING_UNSPLASH_ACCESS_KEY}
logging:
    file:
        name: /var/tmp/eportfolio/server.log
        path: /var/tmp/eportfolio/
    level:
        root: info
        sql: info
        tech:
            eportfolio:
                server: debug
        web: debug
security:
    jwt:
        token:
            refresh: '"local_refresh_key"'
            sign: '"local_signing_key"'
server:
    port: 8090
    tomcat:
        max-swallow-size: -1
    servlet:
        context-path: /api
    host: localhost

spring:
    cache:
        type: redis
    data:
        mongodb:
            auto-index-creation: true
            database: eportfolio-local
            host: localhost
            port: 27017
    mail:
        host: smtp.yandex.com
        password: jxdwlguzlqakqpxx
        port: 465
        properties:
            mail:
                debug: true
                mail:
                    smtp:
                        auth: true
                smtp:
                    auth: true
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory
                        port: 465
                    ssl:
                        enable: true
                    starttls:
                        enable: true
                transport:
                    protocol: smtp
        username: no-reply@eportfolio.tech
    quartz:
        job-store-type: memory
        properties:
            org:
                quartz:
                    scheduler:
                        instanceId: AUTO
                    threadPool:
                        threadCount: 5
    rabbitmq:
        host: ${SPRING_RABBITMQ_HOST}
        password: ${SPRING_RABBITMQ_PASSWORD}
        port: 5672
        username: ${SPRING_RABBITMQ_USERNAME}
    redis:
        host: ${SPRING_REDIS_HOST}
        password: ${SPRING_REDIS_PASSWORD}
        port: 26379
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1