azure:
    storage:
        connectionString: ${SPRING_AZURE_STORAGE_CONNECTION_STRING}
        container:
            name: ${SPRING_AZURE_STORAGE_CONTAINER_NAME}
unsplash:
    access:
        key: ${SPRING_UNSPLASH_ACCESS_KEY}
logging:
    file:
        name: /var/tmp/eportfolio/server.log
        path: /var/tmp/eportfolio/
    level:
        root: info
        sql: error
        tech:
            eportfolio:
                server: info
        web: info
security:
    jwt:
        token:
            refresh: '"This is a refresh token secret"'
            sign: '"This is a JWT secret"'
server:
    port: 8090
    tomcat:
        max-swallow-size: -1
    servlet:
        context-path: /api
    host: eportfolio.tech
spring:
    cache:
        type: redis
    data:
        mongodb:
            auto-index-creation: true
            database: ${SPRING_MONGO_DB_NAME}
            uri: ${SPRING_MONGO_CONNECTION_STRING}
    mail:
        host: smtp.yandex.com
        password: jxdwlguzlqakqpxx
        port: 465
        properties:
            mail:
                debug: true
                mail:
                    smtp:
                        auth: true
                smtp:
                    auth: true
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory
                        port: 465
                    ssl:
                        enable: true
                    starttls:
                        enable: true
                transport:
                    protocol: smtp
        username: no-reply@eportfolio.tech
    quartz:
        job-store-type: memory
        properties:
            org:
                quartz:
                    scheduler:
                        instanceId: AUTO
                    threadPool:
                        threadCount: 5
    rabbitmq:
        host: ${SPRING_RABBITMQ_HOST}
        password: ${SPRING_RABBITMQ_PASSWORD}
        port: ${SPRING_RABBITMQ_PORT}
        username: ${SPRING_RABBITMQ_USERNAME}
    redis:
        host: ${SPRING_REDIS_HOST}
        password: ${SPRING_REDIS_PASSWORD}
        port: ${SPRING_REDIS_PORT}
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
