@startuml

title __HANDLER's Class Diagram__\n

  namespace tech.eportfolio.server {
    namespace common.exception {
      namespace handler {
        class tech.eportfolio.server.common.exception.handler.AuthenticationExceptionHandler {
            {static} + AUTHENTICATION : String
            + handleException()
            + handleException()
        }
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace common.exception {
      namespace handler {
        class tech.eportfolio.server.common.exception.handler.GlobalExceptionHandler {
            + exception()
            + exception()
            + handleAccessDeniedException()
            + handleHttpMessageNotReadable()
            # handleHttpRequestMethodNotSupported()
            # handleMethodArgumentNotValid()
            # handleMissingServletRequestParameter()
        }
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace common.exception {
      namespace handler {
        class tech.eportfolio.server.common.exception.handler.PortfolioExceptionHandler {
            {static} - COMMENT : String
            {static} - LIKE : String
            {static} - PORTFOLIO : String
            + handleException()
            + handleException()
            + handleException()
            + handleException()
        }
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace common.exception {
      namespace handler {
        class tech.eportfolio.server.common.exception.handler.TemplateExceptionHandler {
            + handleException()
            + handleException()
        }
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace common.exception {
      namespace handler {
        class tech.eportfolio.server.common.exception.handler.UserExceptionHandler {
            {static} + USER : String
            + handleException()
            + handleException()
            + handleException()
        }
      }
    }
  }
  

  namespace tech.eportfolio.server {
    namespace common.exception {
      namespace handler {
        class tech.eportfolio.server.common.exception.handler.UserFollowExceptionHandler {
            {static} + FOLLOW : String
            + handleException()
            + handleException()
        }
      }
    }
  }
  

  tech.eportfolio.server.common.exception.handler.GlobalExceptionHandler -up-|> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
